---
title: "Various commands to filter and manipulate seurat objects"
output: html_notebook
---
##Preprocessing data
Ways to reduce data size

```{r}
# preprocessing for T cell
# 1. subsetting base on condition
Tcell_singleR <- subset(Tcell_singleR, timepoint == "A_Pre")

# 2. keep only the assay of interest in the seurat object
DefaultAssay(Tcell_singleR) <- "RNA"
Tcell_singleR <- DietSeurat(Tcell_singleR, assays = "RNA")

# extracting only the needed metadata - nCountRNA, nCountFeature, construct, patient ID, cell subset, response at m6
Tcell_singleR@meta.data <- Tcell_singleR@meta.data[, c(2,3,4,6,45,59)]
# Tcell_singleR@meta.data <- Tcell_singleR@meta.data[, c(1:6,59)]
```

## Extracting the matrix from the seurat object
```{r}

# extracting only the matrix object from the seurat object
mx <- GetAssayData(Tcell_singleR, assay = "RNA", layer = "counts")
Tcell_singleR@meta.data[Tcell_singleR@meta.data$construct %in% c("CAR", "CAR19-22-Bispecific", "CAR19-28Z-Mackall"), ]


# remove rows that are not "genes"
mx <- mx[-which(rownames(mx) %in% c("CAR", "CAR19-22-Bispecific", "CAR19-28Z-Mackall")), ]

# check the dimensions
dim(mx)
Tcell_singleR <- CreateSeuratObject(counts = mx, meta.data = Tcell_singleR@meta.data)
```

## creating a seurat object from matrix
```{r}
# convert assay to v3 assay
Tcell_singleR[["RNA"]] <- as(Tcell_singleR[['RNA']], "Assay")

Tcell_singleR <- NormalizeData(Tcell_singleR) #This will be added to "data" layer
Tcell_singleR <- ScaleData(Tcell_singleR) # This will be added to "scale.data" layer
```

## To use older versions of seurat, might need to downgrade assay version
```{r}
# Test 2: convert assay to v3 assay
pbmc[["RNA"]] <- as(pbmc[['RNA']], "Assay")
```


